skwasjer/MockHttp

src/MockHttp/Extensions/HttpRequestMatcherExtensions.cs, test/MockHttp.Json.Tests/JsonRequestMatchingExtensionTests.cs
I have this use case in my code :
- A call to API with url encoded string content 
- A call to API with a Json content
I wan to verify/mock the API with Json. And I have an exception on the json deserializer. But my second API have not the same uri. 
Why to evaluate other matcher ? If the first is false ?
=> fix: Do not evaluate all matcher when the first is false

src/MockHttp/IO/RateLimitedStream.cs, test/MockHttp.Tests/RateLimitedStreamTests.cs
Usage:
```csharp
Stream stream = ...; // A big stream
mockHttpHandler
.When(matching => ...)
.Respond(new RateLimitedStream(stream, 512000)); // Rate limited to 512 kbps
```
=> feat: add stream that rate limits response streams.

src/MockHttp/Responses/TimeoutBehavior.cs, test/MockHttp.Tests/Responses/TimeoutBehaviorTests.cs
=> Add timeout exception for .NET 5 or greater targets.

.github/workflows/dotnetcore.yml, .github/workflows/sonarcloud.yml, test/Directory.Build.targets, test/MockHttp.Json.Tests/MockHttp.Json.Tests.csproj, test/MockHttp.Testing/MockHttp.Testing.csproj, test/MockHttp.Tests/MockHttp.Tests.csproj
Closes #51 
Added .NET Core 2.1 to test target framework .NET Std 2.0. Requires downgrading some NuGet test dependencies.
=> fix: .NET Standard 2.0 was not covered. 

.github/workflows/dotnetcore.yml, .github/workflows/sonarcloud.yml
Build exception:
```
Testhost process for source(s) '/home/runner/work/MockHttp/MockHttp/test/MockHttp.Json.Tests/bin/Release/net48/MockHttp.Json.Tests.dll' exited with error: Unhandled Exception:
System.TypeInitializationException: The type initializer for 'Microsoft.VisualStudio.TestPlatform.ObjectModel.EqtTrace' threw an exception. ---> System.TypeLoadException: Could not load type of field 'Microsoft.VisualStudio.TestPlatform.ObjectModel.PlatformEqtTrace:TraceSourceLevelsMap' (1) due to: Could not resolve type with token 01000019 from typeref (expected class 'System.Diagnostics.TraceLevel' in assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089') assembly:System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089 …
```
=> ci: .NET Framework test builds fail with .NET 8 SDK preview

.github/workflows/sonarcloud.yml
Fixes PR decoration message
```
warning The version of Java (11.0.20) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.
```
https://docs.sonarcloud.io/appendices/scanner-environment/
=> ci(deps): bump SonarScanner dependencies

src/MockHttp/Http/DataEscapingHelper.cs, test/MockHttp.Tests/Http/DataEscapingHelperTests.cs
Spaces escaped as `+` sign should be parsed into space character allowing the form data matcher to pass.
Fixes #63
=> fix: data escaped space (+) was not parsing into space char.

src/MockHttp.Json/SystemTextJson/JsonDocumentEqualityComparer.cs, src/MockHttp.Json/SystemTextJson/SystemTextJsonEqualityComparer.cs, src/MockHttp.Server/MockHttpServer.cs, src/MockHttp.Server/Server/ServerRequestHandler.cs, src/MockHttp/Extensions/ResponseBuilderExtensions.cs, src/MockHttp/Http/DataEscapingHelper.cs, src/MockHttp/Http/HttpHeadersCollection.cs, src/MockHttp/Matchers/ContentMatcher.cs, src/MockHttp/Matchers/PartialContentMatcher.cs, src/MockHttp/MockHttpHandler.cs, src/MockHttp/NetworkLatency.cs, src/MockHttp/RequestMatching.cs, src/MockHttp/Responses/HttpHeaderBehavior.cs, src/MockHttp/Threading/ConcurrentCollection.cs, test/MockHttp.Server.Tests/Fixtures/MockHttpServerFixture.cs, test/MockHttp.Server.Tests/MockHttpServerTests.cs, test/MockHttp.Testing/DelegateTestCase.cs, test/MockHttp.Testing/NullArgumentTest.cs
* fix(CA2007): ConfigureAwait the task
* style(CA1819): properties should not return arrays
* style(CA1037): overload accepting StringComparison
* style(CA8602): suppress dereference possible null
* style(CA2000): suppress because it is registered for dispose
* style(CA2201): suppress
* style(CA1859): change interface type to concrete type for perf.
* style(CA1054,CA1056): change type of parameter from string to Uri.
* The `MockHttpServer.HostUrl` is deprecated. Use `MockHttpServer.HostUri` instead.
* The `MockHttpServer` ctors accepting `string` URL's are deprecated. Use the overloads accepting `System.Uri`.
* style(CA1861): prefer 'static readonly' fields over constant array args.
* style(CA1860): prefer comparing count to 0 rather using Any()
* style(CA5394): do not use insecure …
=> Address several static code analysis warnings

test/Directory.Build.targets, test/MockHttp.Json.Tests/Extensions/MockHttpRequestContextExtensionsTests.cs, test/MockHttp.Json.Tests/JsonContentMatcherTests.cs, test/MockHttp.Json.Tests/MockConfigurationExtensionsTests.cs, test/MockHttp.Tests/AnyRequestMatchingTests.cs, test/MockHttp.Tests/Extensions/IRespondsExtensionsTests.cs, test/MockHttp.Tests/Extensions/ListExtensionsTests.cs, test/MockHttp.Tests/Extensions/RequestMatchingExtensionsTests.cs, test/MockHttp.Tests/Language/Flow/Response/FuncStreamBodyCannotReadSpec.cs, test/MockHttp.Tests/Language/Flow/Response/NullBuilderTests.cs, test/MockHttp.Tests/Language/Flow/Response/StreamBodyCannotReadSpec.cs, test/MockHttp.Tests/Language/Flow/Response/StreamBodyCannotSeekSpec.cs, test/MockHttp.Tests/Matchers/AnyMatcherTests.cs, test/MockHttp.Tests/Matchers/FakeToStringTestMatcher.cs, test/MockHttp.Tests/Matchers/FormDataMatcherTests.cs, test/MockHttp.Tests/Matchers/HttpRequestMatcherTests.cs, test/MockHttp.Tests/Matchers/NotMatcherTests.cs, test/MockHttp.Tests/MockPriorityBehaviorTests.cs, test/MockHttp.Tests/RateLimitedStreamTests.cs, test/MockHttp.Tests/RequestMatchingTests.cs, test/MockHttp.Tests/Responses/EmptyContentTests.cs, test/MockHttp.Tests/Responses/TimeoutBehaviorTests.cs
See https://github.com/moq/moq/issues/1372
=> test: replace Moq with NSubstitute

src/MockHttp.Server/Server/HttpResponseMessageExtensions.cs, src/MockHttp/Http/HttpHeaderEqualityComparer.cs, src/MockHttp/HttpMockException.cs, src/MockHttp/Responses/HttpHeaderBehavior.cs, test/MockHttp.Json.Tests/ArgAny.cs, test/MockHttp.Json.Tests/JsonContentMatcherTests.cs, test/MockHttp.Tests/Language/Flow/Response/HeaderSpec.cs
* refactor(CA2208): throw invalid enum exception in ctor to satisfy static code analysis.
* fix(SYSLIB0051): mark serializable/binary formatter support as obsolete
* refactor(CA1031): use `TryAddWithoutValidation` to avoid exceptions and to skip adding header if not supported.
* fix(CA2007): use `ConfigureAwait` on awaitable async stream
* test(CS8604): in older runtimes, IEqualityComparer<> did not use nullable annotation. Fix with string polyfill for Arg.Any.
=> fix: address some static code analysis issues, exposed by the latest analyzer

src/MockHttp.Server/MockHttpServer.cs, test/MockHttp.Server.Tests/MockHttpServerTests.cs
Fixes some async issues with starting and stopping the `MockHttpServer`:
- The `MockHttpServer.StopAsync` method was not properly awaiting the inner `host.StopAsync` and disposing the host in the finally block. 
```csharp
try
{
return host.StopAsync(cancellationToken);  // Returning a task without awaiting.
}
finally
{
host.Dispose(); // But then disposing.
}
```
- `lock(object) { }` is not supported in async context so replaced it with a `SemaphoreSlim`.
- The `StartAsync`/`StopAsync` methods no longer throw when called multiple times, and instead just return without doing anything.
=> fix(server): `MockHttpServer.StopAsync` disposes the host before it has a change to actually stop. 

src/MockHttp.Server/MockHttpServer.cs, test/MockHttp.Server.Tests/Fixtures/MockHttpServerFixture.cs, test/MockHttp.Server.Tests/MockHttpServerTests.cs
Added `IAsyncDisposable` to asynchronously dispose `HttpMockServer` and the internal host.
=> feat(server): implement `IAsyncDisposable` on `HttpMockServer`

src/MockHttp/IO/RateLimitedStream.cs, test/MockHttp.Tests/RateLimitedStreamTests.cs
=> feat: add ctor parameter to keep the underlying stream open on disposal

src/MockHttp/Extensions/ResponseBuilderExtensions.cs, src/MockHttp/Language/Flow/Response/ResponseBuilder.cs, src/MockHttp/Responses/BitRate.cs, src/MockHttp/Responses/TransferRateBehavior.cs, test/MockHttp.Tests/Language/Flow/Response/NullBuilderTests.cs, test/MockHttp.Tests/Language/Flow/Response/TransferRateSpec.cs, test/MockHttp.Tests/Language/Flow/Response/TransferRateSpec2.cs, test/MockHttp.Tests/Language/Flow/Response/TransferRateWithMultipleRequestsSpec.cs, test/MockHttp.Tests/Language/Flow/Response/TransferRateWithOutOfRangeBitRateSpec.cs, test/MockHttp.Tests/MockHttpHandlerTests.cs, test/MockHttp.Tests/Responses/BitRateTests.cs
=> feat: adds transfer rate extension

src/MockHttp.Server/MockHttpServer.cs, src/MockHttp.Server/Server/ExceptionHandler.cs, src/MockHttp.Server/Server/ServerRequestHandler.cs, test/MockHttp.Server.Tests/MockHttpServerTests.cs
Fix CA1031 warning. This also avoids unnecessary allocation of new `HttpResponseMessage`.
=> fix(CA1031): use exception handler middleware instead of catching all exceptions in ServerRequestHandler

src/MockHttp/Matchers/Patterns/RegexPatternMatcher.cs, src/MockHttp/Matchers/Patterns/WildcardPatternMatcher.cs, test/MockHttp.Tests/Matchers/Patterns/WildcardPatternMatcherTests.cs
F.ex.:
`path/file.jpg?width=*` was previously converted to a regex `^(path/file.jpg?width=).*`. This has a few problems:
- the `.` (dot) in the filename matches ANY character in that position
- the `?` makes the preceding `g` in `jpg` an optional character so just `jp` matches just as well.
All special regex characters are now escaped to ensure an exact matching character.
=> fix: wildcard match does not escape special regex characters

.github/workflows/codeql-analysis.yml, .github/workflows/main.yml, .github/workflows/sonarcloud.yml, examples/Minimal API/MyWebApp.Tests/MyWebApp.Tests.csproj, examples/Minimal API/MyWebApp.Tests/SmokeTests.cs, examples/Minimal API/MyWebApp/MyWebApp.csproj, src/MockHttp.Json/MockHttp.Json.csproj, src/MockHttp.Server/MockHttp.Server.csproj, src/MockHttp/Matchers/Patterns/RegexPatternMatcher.cs, src/MockHttp/MockHttp.csproj, test/MockHttp.Json.Tests/MockHttp.Json.Tests.csproj, test/MockHttp.Server.Tests/MockHttp.Server.Tests.csproj, test/MockHttp.Testing/MockHttp.Testing.csproj, test/MockHttp.Tests/Http/HttpHeadersCollectionTests.cs, test/MockHttp.Tests/MockHttp.Tests.csproj
- removes the .NET 7 target
- updates the example to .NET 8
=> chore: remove .NET 7 since this is now EOL

test/Directory.Build.targets, test/MockHttp.Server.Tests/Fixtures/CapturingLoggerFactoryFixture.cs, test/MockHttp.Server.Tests/Fixtures/LoggerFactoryFixture.cs, test/MockHttp.Server.Tests/Fixtures/MockHttpServerFixture.cs, test/MockHttp.Server.Tests/MockHttp.Server.Tests.csproj, test/MockHttp.Testing/MockHttp.Testing.csproj
- bump test dependencies xunit, Microsoft.NET.Test.Sdk and, Newtonsoft.Json
- replaced test dependencies Serilog (etc) with own logging capture impl.
=> chore(deps): bump test dependencies

.github/workflows/codeql-analysis.yml
CodeQL is a required job for PR merges. Without this upgrade, all other PR's cannot be automatically merged.
=> ci: update CodeQL to v3

src/MockHttp.Json/Extensions/ResponseBuilderExtensions.cs, src/MockHttp/Internal/Response/Behaviors/HttpContentBehavior.cs, src/MockHttp/Internal/Response/Behaviors/HttpHeaderBehavior.cs, src/MockHttp/Internal/Response/Behaviors/NetworkLatencyBehavior.cs, src/MockHttp/Internal/Response/Behaviors/StatusCodeBehavior.cs, src/MockHttp/Internal/Response/Behaviors/TimeoutBehavior.cs, src/MockHttp/Internal/Response/Behaviors/TransferRateBehavior.cs, src/MockHttp/Language/Flow/Response/EnsureHttpContentBehavior.cs, src/MockHttp/Responses/IResponseBehavior.cs, test/MockHttp.Tests/PublicApi/.NET_8.0.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.6.2.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.7.2.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.8.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Standard_2.0_via_.NET_Framework_4.8.1.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Standard_2.1_via_.NET_6.0.verified.txt
Renamed the method argument `next` to `nextHandler` to satisfy rule [CA1716](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1716).
=> fix(CA1716)!: do not use reserved language keyword 'Next'

src/MockHttp.Json/Extensions/ResponseBuilderExtensions.cs, src/MockHttp/Internal/Response/Behaviors/HttpContentBehavior.cs, src/MockHttp/Internal/Response/Behaviors/HttpHeaderBehavior.cs, src/MockHttp/Internal/Response/Behaviors/NetworkLatencyBehavior.cs, src/MockHttp/Internal/Response/Behaviors/StatusCodeBehavior.cs, src/MockHttp/Internal/Response/Behaviors/TimeoutBehavior.cs, src/MockHttp/Internal/Response/Behaviors/TransferRateBehavior.cs, src/MockHttp/Language/Flow/Response/EnsureHttpContentBehavior.cs, src/MockHttp/Language/Flow/Response/ResponseBuilder.cs, src/MockHttp/Responses/IResponseBehavior.cs, test/MockHttp.Tests/Internal/Response/Behaviors/TimeoutBehaviorTests.cs, test/MockHttp.Tests/PublicApi/.NET_8.0.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.6.2.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.7.2.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Framework_4.8.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Standard_2.0_via_.NET_Framework_4.8.1.verified.txt, test/MockHttp.Tests/PublicApi/.NET_Standard_2.1_via_.NET_6.0.verified.txt
Renamed `ResponseHandlerDelegate` to `ResponseHandler` to satisfy [CA1711](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1711).
=> fix(CA1711)!: delegate names should not end with Delegate.
